import 'package:flutter/material.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/Generated3592836basedatadocumentofficepagepaper_1077821Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedKULITASJARINGANWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedHourglass_emptyWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedDATABLANKSPOTWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedPENGADUANWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedSiKoJOnWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedLonceng1Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedNotifications_noneWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedAktifitasWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedAuricularphonesymbolinacircle_iconicons1Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedDATAMENARAWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedNotifikasiWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedAsn1Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedPerm_identityWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedDATAVISATWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedSISTEMINFORMASIKOMUNIKASIJARINGANONLINEWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedParabolicantenna_1183761Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedAntenna_1029321Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedINFORMASIINFRASTRUTURWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedProfilWidget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/sikojonapp/generatedandroid2widget/generated/GeneratedSignalcellularconnectednointernet0bar_1186501Widget.dart';

/* Frame Android - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 824.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 4.0,
                top: -3.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 181.0,
                child: GeneratedAsn1Widget(),
              ),
              Positioned(
                left: -9.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 186.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 236.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 39.0,
                child: GeneratedSISTEMINFORMASIKOMUNIKASIJARINGANONLINEWidget(),
              ),
              Positioned(
                left: 134.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 30.0,
                child: GeneratedSiKoJOnWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 61.0,
                child: GeneratedGroup18Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 767.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 41.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 107.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 107.0,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 131.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 107.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 250.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 107.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 131.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 107.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 250.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 107.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 228.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 82.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedHourglass_emptyWidget(),
              ),
              Positioned(
                left: 68.0,
                top: 794.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 19.0,
                child: GeneratedAktifitasWidget(),
              ),
              Positioned(
                left: 246.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNotifications_noneWidget(),
              ),
              Positioned(
                left: 232.0,
                top: 793.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 19.0,
                child: GeneratedNotifikasiWidget(),
              ),
              Positioned(
                left: 313.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPerm_identityWidget(),
              ),
              Positioned(
                left: 310.0,
                top: 792.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 19.0,
                child: GeneratedProfilWidget(),
              ),
              Positioned(
                left: 126.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 117.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 37.0,
                child: GeneratedDATAMENARAWidget(),
              ),
              Positioned(
                left: 260.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 21.0,
                child: GeneratedPENGADUANWidget(),
              ),
              Positioned(
                left: 129.0,
                top: 461.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 28.0,
                child: GeneratedINFORMASIINFRASTRUTURWidget(),
              ),
              Positioned(
                left: 160.0,
                top: 334.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 37.0,
                child: GeneratedDATAVISATWidget(),
              ),
              Positioned(
                left: 258.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 34.0,
                child: GeneratedDATABLANKSPOTWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 34.0,
                child: GeneratedKULITASJARINGANWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1527777777777778;

                  final double height =
                      constraints.maxHeight * 0.05825242718446602;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08333333333333333,
                        y: constraints.maxHeight * 0.3470873786407767,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              Generated3592836basedatadocumentofficepagepaper_1077821Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1638888888888889;

                  final double height =
                      constraints.maxHeight * 0.06674757281553398;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.4305555555555556,
                        y: constraints.maxHeight * 0.33859223300970875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedParabolicantenna_1183761Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1527777777777778;

                  final double height =
                      constraints.maxHeight * 0.06067961165048544;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7416666666666667,
                        y: constraints.maxHeight * 0.33859223300970875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedSignalcellularconnectednointernet0bar_1186501Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.16666666666666666;

                  final double height =
                      constraints.maxHeight * 0.07160194174757281;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.075,
                        y: constraints.maxHeight * 0.4866504854368932,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAntenna_1029321Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1638888888888889;

                  final double height =
                      constraints.maxHeight * 0.061893203883495146;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.4305555555555556,
                        y: constraints.maxHeight * 0.49150485436893204,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLonceng1Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.15555555555555556;

                  final double height =
                      constraints.maxHeight * 0.0703883495145631;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7611111111111111,
                        y: constraints.maxHeight * 0.49150485436893204,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedAuricularphonesymbolinacircle_iconicons1Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
